// This file is autogenerated. Do not edit directly!
#pragma once
#include <stdint.h>

struct ThunkMetadata
{
    const char* mName;
    const char* mPattern;
    int64_t mOffset;
    uintptr_t* mPointer;
};

#define DX_CREATE_DYNAMIC_THUNK(mangled_symbol, lookup_name, pattern_str, offset) \
    extern "C" uintptr_t impl_##mangled_symbol; \
    uintptr_t impl_##mangled_symbol = 0; \
    \
    [[gnu::used, gnu::section("dx_thunks")]] \
    static const ThunkMetadata meta_##mangled_symbol = { \
        lookup_name, \
        pattern_str, \
        offset, \
        &impl_##mangled_symbol \
    }; \
    \
    extern "C" __attribute__((visibility("hidden"))) void mangled_symbol(); \
    \
    __asm__ ( \
        ".section .text." #mangled_symbol "\n" \
        ".global " #mangled_symbol "\n" \
        ".hidden " #mangled_symbol "\n" \
        ".type " #mangled_symbol ", %function\n" \
        #mangled_symbol ":\n" \
        "adrp x16, impl_" #mangled_symbol "\n" \
        "ldr x16, [x16, #:lo12:impl_" #mangled_symbol "]\n" \
        "br x16\n" \
    );

DX_CREATE_DYNAMIC_THUNK(
    _ZN4gear11GetRaceInfoEv,
    "_ZN4gear11GetRaceInfoEv",
    "8C 01 0B 9B 8C 45 40 B9 2D 00 40 B9 9F 01 0D 6B 08 15 88 1A 5F 01 09 EB EB FE FF 54 02 00 00 14",
    0x2c
)

DX_CREATE_DYNAMIC_THUNK(
    _ZN5audio12AudSceneRace20prepareRaceSceneBgm_Ev,
    "_ZN5audio12AudSceneRace20prepareRaceSceneBgm_Ev",
    "61 0A 41 B9 21 12 F8 37 19 8B FF 97 7F A2 04 39 68",
    -0x24
)

DX_CREATE_DYNAMIC_THUNK(
    _ZN2ui9Page_Race9onCreate_Ev,
    "_ZN2ui9Page_Race9onCreate_Ev",
    "F5 03 00 AA E8 07 00 32 E0 03 00 91 E8 03 00 B9",
    -0x2c
)

DX_CREATE_DYNAMIC_THUNK(
    _ZN4gear16GetPlayerManagerEv,
    "_ZN4gear16GetPlayerManagerEv",
    "00 00 44 F9 FD 7B C1 A8 C0 03 5F D6 FD 7B BF A9 FD 03 00 91",
    -0x10
)

DX_CREATE_DYNAMIC_THUNK(
    _ZN2ui17Control_RaceTimer5onIn_Ev,
    "_ZN2ui17Control_RaceTimer5onIn_Ev",
    "68 5E 00 F9 69 76 C3 39 0A 61 40 B9 5F 01 09 6B 44 81 49 7A",
    -0x74
)

DX_CREATE_DYNAMIC_THUNK(
    _ZN4gear11NetworkUtil14getMyKartIndexEv,
    "_ZN4gear11NetworkUtil14getMyKartIndexEv",
    "A9 C3 1F 38 00 01 3F D6 FD 7B 41 A9 00 1C 00 13",
    -0x2c
)

DX_CREATE_DYNAMIC_THUNK(
    _ZN4gear6UIUtil16getFullNumberStrEPN4sead22BufferedSafeStringBaseIDsEEij,
    "_ZN4gear6UIUtil16getFullNumberStrEPN4sead22BufferedSafeStringBaseIDsEEij",
    "15 01 00 79 28 41 00 91 E2 03 14 AA E8 07 00 F9",
    -0x80
)

DX_CREATE_DYNAMIC_THUNK(
    _ZN4gear9UIControl10setMessageEPN2nn4ui2d4PaneEPKDs,
    "_ZN4gear9UIControl10setMessageEPN2nn4ui2d4PaneEPKDs",
    "68 02 40 F9 04 89 40 F9 E3 03 00 2A E0 03 13 AA E1 03 14 AA E2 03 1F 2A",
    -0xd4
)

DX_CREATE_DYNAMIC_THUNK(
    _ZNK4gear9UIControl8findPaneERKN4sead14SafeStringBaseIcEE,
    "_ZNK4gear9UIControl8findPaneERKN4sead14SafeStringBaseIcEE",
    "14 0D 40 F9 88 02 40 F9 00 31 40 F9 E0 07 00 F9 68 02 40 F9 08 0D 40 F9 E0 03 13 AA 00 01 3F D6",
    -0x1c
)

DX_CREATE_DYNAMIC_THUNK(
    _ZN2ui19Control_RaceLapCoin7onInit_Ev,
    "_ZN2ui19Control_RaceLapCoin7onInit_Ev",
    "69 4E 43 39 0A 61 40 B9 5F 01 09 6B 44 81 49 7A",
    -0x7c
)

DX_CREATE_DYNAMIC_THUNK(
    _ZN2ui19Control_RaceLapCoin7onCalc_Ev,
    "_ZN2ui19Control_RaceLapCoin7onCalc_Ev",
    "FF 03 02 D1 F4 4F 06 A9 FD 7B 07 A9 FD C3 01 91 F3 03 00 AA 68 5E 40 F9 14 41 41 39 68 42 43 39",
    0x0
)

DX_CREATE_DYNAMIC_THUNK(
    _ZN4gear13FrameworkUtil19getCurrentGameSceneEv,
    "_ZN4gear13FrameworkUtil19getCurrentGameSceneEv",
    "08 01 40 F9 08 11 40 F9 08 05 40 F9 09 01 46 39 3F 01 1E 72 E0 03 88 9A",
    -0x8
)
